# Autogenerated wrapper script for Libuuid_jll for armv7l-linux-gnueabihf
export libuuid

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"
LIBPATH_default = ""

# Relative path to `libuuid`
const libuuid_splitpath = ["lib", "libuuid.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libuuid_path = ""

# libuuid-specific global declaration
# This will be filled out by __init__()
libuuid_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libuuid = "libuuid.so.1"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"Libuuid")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global libuuid_path = normpath(joinpath(artifact_dir, libuuid_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libuuid_handle = dlopen(libuuid_path)
    push!(LIBPATH_list, dirname(libuuid_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(vcat(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ':')

    
end  # __init__()

